### ISSUE TITLE
NoMethodError 'pinyin'

### ISSUE THREAD

**Issue by aoc** [zeyuLiang/redmine_customized_report#1]
After I clicked on custom_report on issues page I get a 500 error and this is what I found in the log:

<pre>Completed 500 Internal Server Error in 20.6ms

NoMethodError (undefined method `pinyin' for #<User:0x007fb298b7fd98>):
  app/models/query.rb:329:in `available_filters'
  app/models/query.rb:220:in `build_from_params'</pre>

**Comment by jasir** [comment]
Same for me.

**Comment by zeyuLiang** [comment]
got it.l will fix it asap.

来自 MEIZU MX

-------- 原始邮件 --------
发件人：jasir notifications@github.com
时间：周六 5月31日 06:27
收件人：zeyuLiang/redmine_customized_report redmine_customized_report@noreply.github.com
主题：Re: [redmine_customized_report] NoMethodError 'pinyin' (#1)

Same for me.

**Comment by zeyuLiang** [comment]
this problem is fixed. My redmine is deeply customized, so the plugin developed on it may not work on the original redmine..

**Comment by aoc** [comment]
thanks. It's working now!
